services:
  yahaha-cover-studio:
    build: .
    image: ghcr.io/justzerock/yahaha-cover-studio:latest
    container_name: yahaha-cover-studio
    platform: linux/arm64
    ports:
      - "8899:8080"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
