<template>
  <Teleport to="body"><nav class="yh-settings-anchor" :style="{ left: `${navLeft}px` }" :data-mcr-theme="theme" aria-label="设置分组导航">
    <v-tooltip v-for="section in sections" :key="section.id" location="end" :open-delay="220"><template #activator="{ props: tooltipProps }"><button v-bind="tooltipProps" type="button" class="yh-settings-anchor__button" :class="{ 'is-active': activeId === section.id }" :aria-label="`跳转到${section.label}`" :aria-current="activeId === section.id ? 'true' : undefined" @click="scrollToSection(section.id)"><span class="yh-settings-anchor__line" aria-hidden="true" /></button></template><span>{{ section.label }}</span></v-tooltip>
  </nav></Teleport>
</template>
<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
export interface SettingsAnchorSection { id: string; label: string }
const props = withDefaults(defineProps<{ sections: SettingsAnchorSection[]; contentElement?: HTMLElement | null; scrollContainer?: HTMLElement | null; topOffset?: number; theme?: 'light' | 'dark' }>(), { contentElement: null, scrollContainer: null, topOffset: 96, theme: 'light' })
const activeId = ref(props.sections[0]?.id || ''), navLeft = ref(12)
let observer: IntersectionObserver | null = null, resizeObserver: ResizeObserver | null = null, resolvedScrollContainer: HTMLElement | null = null, clickLockUntil = 0, clickUnlockTimer: number | null = null
function observedElements() { return props.sections.map((section) => document.getElementById(section.id)).filter((element): element is HTMLElement => Boolean(element)) }
function findScrollContainer(element: HTMLElement | null) { let current = element?.parentElement || null; while (current) { const style = getComputedStyle(current); if (/(auto|scroll)/.test(`${style.overflowY} ${style.overflow}`) && current.scrollHeight > current.clientHeight) return current; current = current.parentElement } return null }
function updatePosition() { const rect = props.contentElement?.getBoundingClientRect(); navLeft.value = rect ? Math.max(12, Math.round(rect.left - 46)) : 12; resolvedScrollContainer = props.scrollContainer || findScrollContainer(props.contentElement || observedElements()[0] || null) }
function setupObserver() { observer?.disconnect(); updatePosition(); const elements = observedElements(); if (!elements.length || typeof IntersectionObserver === 'undefined') return; observer = new IntersectionObserver((entries) => { if (Date.now() < clickLockUntil) return; const root = resolvedScrollContainer; const reachedBottom = root ? root.scrollTop + root.clientHeight >= root.scrollHeight - 2 : window.scrollY + window.innerHeight >= document.documentElement.scrollHeight - 2; if (reachedBottom && props.sections.length) { activeId.value = props.sections.at(-1)?.id || activeId.value; return } const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => Math.abs(a.boundingClientRect.top - props.topOffset) - Math.abs(b.boundingClientRect.top - props.topOffset)); if (visible[0]?.target.id) activeId.value = visible[0].target.id }, { root: resolvedScrollContainer, rootMargin: `-${props.topOffset}px 0px -62% 0px`, threshold: [0,.05,.25,.6] }); elements.forEach((element) => observer?.observe(element)) }
function scrollToSection(id: string) { const target = document.getElementById(id); if (!target) return; activeId.value = id; clickLockUntil = Date.now() + 1800; if (resolvedScrollContainer) { const rootRect = resolvedScrollContainer.getBoundingClientRect(), targetRect = target.getBoundingClientRect(); resolvedScrollContainer.scrollTo({ top: resolvedScrollContainer.scrollTop + targetRect.top - rootRect.top - props.topOffset, behavior: 'smooth' }) } else target.scrollIntoView({ behavior: 'smooth', block: 'start' }); if (clickUnlockTimer !== null) window.clearTimeout(clickUnlockTimer); clickUnlockTimer = window.setTimeout(() => { activeId.value = id; clickUnlockTimer = null }, 950) }
watch(() => [props.sections, props.scrollContainer, props.contentElement], () => void nextTick(setupObserver), { deep: true })
onMounted(() => void nextTick(() => { setupObserver(); if (typeof ResizeObserver !== 'undefined' && props.contentElement) { resizeObserver = new ResizeObserver(setupObserver); resizeObserver.observe(props.contentElement) } window.addEventListener('resize', setupObserver) }))
onBeforeUnmount(() => { observer?.disconnect(); resizeObserver?.disconnect(); window.removeEventListener('resize', setupObserver); if (clickUnlockTimer !== null) window.clearTimeout(clickUnlockTimer) })
</script>
<style scoped>
.yh-settings-anchor { position: fixed; top: 50%; z-index: 28; width: 36px; height: max-content; margin: 0; padding: 4px 0; background: transparent; transform: translateY(-50%); }.yh-settings-anchor__button { width: 34px; height: 32px; display: grid; place-items: center; padding: 0; border: 0; background: transparent; cursor: pointer; }.yh-settings-anchor__line { width: 16px; height: 2px; border-radius: 999px; background: rgba(60,60,67,.25); transition: width 180ms ease, opacity 180ms ease, background-color 180ms ease, transform 180ms ease; }.yh-settings-anchor__button:hover .yh-settings-anchor__line,.yh-settings-anchor__button:focus-visible .yh-settings-anchor__line { width: 24px; background: rgba(60,60,67,.55); }.yh-settings-anchor__button.is-active .yh-settings-anchor__line { width: 32px; background: var(--color-primary,#4f8cff); opacity: 1; transform: translateX(2px); }.yh-settings-anchor__button:focus-visible { outline: 2px solid color-mix(in srgb,var(--color-primary,#4f8cff) 42%,transparent); outline-offset: -3px; border-radius: 10px; }:global([data-mcr-theme="dark"]) .yh-settings-anchor__line { background: rgba(235,235,245,.22); }:global([data-mcr-theme="dark"]) .yh-settings-anchor__button.is-active .yh-settings-anchor__line { background: var(--color-primary,#6ea2ff); }@media (max-width:1023px){.yh-settings-anchor{display:none}}@media (prefers-reduced-motion:reduce){.yh-settings-anchor__line{transition:none}}
</style>
